# Generated by Django 2.1 on 2018-08-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='post_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
